<?php

namespace QueryOrm\ldap\active_directory;

use QueryOrm\ldap\LdapSelector;
use QueryOrm\Model;

class ActiveDirectorySelector extends LdapSelector
{
	/** @var string[] $fields */
	private array $fields;

	public function __construct(string $model, string ...$fields)
	{
		parent::__construct($model, ...$fields);
		$this->fields = $fields;
	}

	public function execute()
	{
		parent::execute(); // TODO: Change the autogenerated stub
	}
}